### PR TITLE
Add support for creating a thumbnail

### PR DESCRIPTION
**Pull request by Jumhyn**
#### Pull Request Checklist

- [ ] Resolved any merge conflicts
- [ ] No build errors or warnings are introduced
- [ ] New files are written in Swift
- [ ] New classes contain license headers
- [ ] New classes have Documentation
- [ ] New public methods have Documentation

#### Issue Summary

- Add a request that will create a thumbnail on the specified video.

#### Implementation Summary

- Add a new method `createPictureRequest(forVideoURI:)`.

#### How to Test

- Build and run tests.

### CODE REVIEW

**Comment by cameo-github** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Executed 180 tests, with 0 failures (0 unexpected) in 1.163 (1.339) seconds</td>
    </tr>
  </tbody>
</table>

See build details on [CircleCI](https://circleci.com/gh/vimeo/VimeoNetworking/1558)

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by supperspidey — APPROVED** [review]
Thanks for jumping into this work so quickly @Jumhyn . This looks fine for me. Should we also add another API for uploading a picture?

**Comment by Jumhyn** [comment]
Thanks @supperspidey! I was thinking about that and am interested to know your thoughts. The photo upload itself doesn't really interface with our API--the flow is that we create the thumbnail without specifying time/active, and then we just make a POST request to the link that gets returned to upload the thumbnail. A simple `URLSessionTask` should be enough for this, so I don't know if it's necessary to have it in VimeoNetworking.

**Comment by supperspidey** [comment]
I see. Okay, let's roll this API out for now, and if in the future third party devs want support for uploading pictures, then we'll work on that :)

**Pull request merged**
