### PR TITLE
Cameo-specific requirements

### PR DESCRIPTION
**Pull request by alfiehanssen**
It appears that this branch is used in Cameo and therefore should be merged to `master`.

### CODE REVIEW

**Comment by alfiehanssen** [comment]
@mikew-personal Can you take over this PR and get it merged? It seems like it needs to be merged but I'm not familiar with its history...

**Comment by alfiehanssen** [comment]
@mikew-personal What's the fate / purpose of this branch (see comment above)?

**Comment by mikew-personal** [comment]
@alfiehanssen I'll review this branch again.  It may have specific changes that we needed for the Cameo 2.3.0 release that we didn't want merged back to master.

**Comment by alfiehanssen** [comment]
@mikew-personal Can you merge or close this PR (and delete the branch) this week?

**Comment by ghking** [comment]
Looks good to me 👍

**Comment by mikew-personal** [comment]
This looks good to me too, I tested with Cameo and everything there is still building so I think we're good to go. @ghking @alfiehanssen

**Pull request merged**
