### PR TITLE
Fix #34: VimeoNetworking.h file not found after pod install

### LINKED ISSUE #34: VimeoNetworking.h file not found
#### Issue Summary
Adding and using VimeoNetworking (v0.0.1) as a (git) pod dependency result in the following error: 
```
VimeoNetworking-Swift.h: 100:9: 'VimeoNetworking/VimeoNetworking.h' file not found
```
#### Reproduction Steps
- Create a new tvOS project (Single View Application) and add the following dependency to your pod file:
```pod 'VimeoNetworking', :git => 'https://github.com/vimeo/VimeoNetworking.git' ```
- Run the pod install command
- Open the generated workspace
- Import VimeoNetworking in your AppDelegate
- Create, let say, an AppConfiguration object in didFinishLaunchingWithOptions (for the sake of issue reproduction)
- Build the project

#### Expected Behavior
Build should terminate without any error

#### Actual Behavior
Build failed with the following stack trace:
```
<module-includes>:2:9: note: in file included from <module-includes>:2:
#import "Headers/VimeoNetworking-Swift.h"
        ^
../Debug-appletvos/VimeoNetworking/VimeoNetworking.framework/Headers/VimeoNetworking-Swift.h: 100:9: error: 'VimeoNetworking/VimeoNetworking.h' file not found
#import <VimeoNetworking/VimeoNetworking.h>
        ^
<unknown>:0: error: could not build Objective-C module 'VimeoNetworking'
```
After a quick check it appears that the missing file is excluded on purpose from the podspec. Deleting the following line in the podspec:
```
s.exclude_files = "VimeoNetworking/VimeoNetworking/VimeoNetworking.h" (line 24)
```
and pod installing the modified local pod seems to resolve the issue. If removing the line is something that you would consider let me know and I will create a PR for this fix.

Notes: 
- I did not test this with an iOS project but I guess result will be the same.
- iOS example in the repo build successfully.

### PR DESCRIPTION
**Pull request by nicolasabric**

### CODE REVIEW

**Comment by alfiehanssen** [comment]
@huebnerob Is it not possible to merge this change until Vimeo-iOS drops iOS7 support?

**Comment by huebnerob** [comment]
@alfiehanssen I don't think we'll be intending to use this library with iOS 7 anyway

**Comment by huebnerob** [comment]
I'll try this change with our projects and see how it sits, stay tuned.

**Comment by nicolasabric** [comment]
@alfiehanssen @huebnerob thank you guys! Just let me know if I need to update the PR in any way.

**Comment by huebnerob** [comment]
@nicolasabric I got the chance to test this with some of our projects and ran into problems.  Namely that the `VimeoNetworking/File.h` imports seem to conflict with the way cocoapods imports files.

screen shot 2016-06-30 at 11 26 11 am

Are you not seeing issues similar to this? Also, why did you find it necessary to include this file?

**Comment by nicolasabric** [comment]
@huebnerob sorry for the late reply I was off last couple of days. 
- **Are you not seeing issues similar to this?** No I do not experience this error when removing the ``` s.exclude_files = "VimeoNetworking/VimeoNetworking/VimeoNetworking.h"``` line from the podspec. 
- **why did you find it necessary to include this file?** Without this include I m not able to use the pod. I get the following error when compiling

screen shot 2016-07-04 at 16 42 53

FYI this is my pod file and my pod version is 1.0.1:

```
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
platform :tvos, '9.0'

target 'OdysseyTV' do
  pod 'Socket.IO-Client-Swift', '~> 4.1.6'
  pod 'SwiftyJSON', '~> 2.3.2'
  pod 'SDWebImage', '~> 3.8.1'
#pod 'VimeoNetworking', :git => 'https://github.com/nicolasabric/VimeoNetworking.git'
  pod 'VimeoNetworking', :git => 'https://github.com/vimeo/VimeoNetworking.git'
  pod 'TVOSButton', '~> 0.4'
  pod 'Charts/Realm', '~> 2.2.5'
end
```

I am just doing ```pod install``` and then use the generated workspace. I did not add bridging headers myself (if that matters?), just using the generated workspace and try to compile. This error disappear when I m using my own fork in which I removed the ```s.exclude_files``` line.

**Comment by huebnerob** [comment]
Hi @nicolasabric,

After a bit of research, it seems that updating our cocoapods install to 1.0+ and implementing this change does indeed fix the issue you're describing. Merging this now, thanks for your patience!

cc @alfiehanssen @mikew-personal Let me know if you run into issues with Cameo, I was able to resolve everything in the tvOS project between both local and buildbot by updating to cocoapods 1.0.0

**Pull request merged**
