### PR TITLE
VIM-4790: Keychain Fix

### PR DESCRIPTION
**Pull request by ghking**
#### Ticket

https://vimean.atlassian.net/browse/VIM-4790

#### Ticket Summary

VimeoNetworking was previously using a different keychain configuration to store accounts than VIMNetworking. This PR reverts that change. This allows for seamless migrations from VIMNetworking to VimeoNetworking.

#### Implementation Summary

Modified the keychain keys. Also removed the default keychain values from AppConfiguration.

#### How to Test

Logged in, migrate from 6.1.3 to 6.1.4. You should remain logged in.

### CODE REVIEW

**Comment by ghking** [comment]
cc @alfiehanssen

**Comment by alfiehanssen** [comment]
❤️  it! Is there an app PR?

**Comment by ghking** [comment]
@alfiehanssen yeah cc'd ya

**Comment by ghking** [comment]
@alfiehanssen 
https://github.vimeows.com/MobileApps/Vimeo-tvOS/pull/200
https://github.vimeows.com/MobileApps/Vimeo-iOS/pull/1079

**Pull request merged**
