### PR TITLE
Removes triggers related dead code from library

### PR DESCRIPTION
**Pull request by rpassis**
#### Ticket

N/A

#### Ticket Summary

- Removes unused code related to notification `Triggers` from the app

#### How to Test

- Ensure this builds and all tests pass

### CODE REVIEW

**Comment by cameo-github** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">SwiftLint not installed, download from https://github.com/realm/SwiftLint</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Executed 118 tests, with 0 failures (0 unexpected) in 1.730 (2.107) seconds</td>
    </tr>
  </tbody>
</table>

See build details on [CircleCI](https://circleci.com/gh/vimeo/VimeoNetworking/1439)

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by Jumhyn — COMMENTED** [review]
LGTM

**Comment by rpassis** [comment]
@Jumhyn could I please get a ✅ here?

**Review by Jumhyn — APPROVED** [review]

**Comment by rpassis** [comment]
Thank you!

**Pull request merged**
